backend/src/yowiz.ts, generator-foodq/generators/app/index.js
See https://github.com/SAP/yeoman-ui/issues/11
=> Added example to foodq of an async inquirer method

backend/src/yeomanui.ts
Made reading description from package.json work also in vs code extensions
=> Read generator description from package.json

frontend/src/App.vue, frontend/src/components/Done.vue, frontend/src/components/Header.vue, frontend/src/components/Navigation.vue, frontend/src/components/QuestionTypeSelector.vue, frontend/src/components/QuestionTypes/GeneratorSelection.vue, frontend/src/components/QuestionTypes/QuestionCheckbox.vue, frontend/src/components/QuestionTypes/QuestionConfirm.vue, frontend/src/components/QuestionTypes/QuestionEditor.vue, frontend/src/components/QuestionTypes/QuestionExpand.vue, frontend/src/components/QuestionTypes/QuestionInput.vue, frontend/src/components/QuestionTypes/QuestionList.vue, frontend/src/components/Step.vue, frontend/src/main.js, frontend/src/plugins/vuetify.js, frontend/tests/components/Done.spec.js, frontend/tests/components/QuestionTypes/QuestionCheckbox.spec.js, frontend/tests/components/QuestionTypes/QuestionExpand.spec.js, frontend/tests/components/QuestionTypes/QuestionInput.spec.js, frontend/tests/components/QuestionTypes/QuestionList.spec.js
*Final colors alignment is in process
=> Align next button + cards + inputs + overall

backend/package.json
Should solve issue https://github.com/SAP/yeoman-ui/issues/87
Update 1.39.2: The update addresses these issues 
https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22September+2019+Recovery+2%22+is%3Aclosed .
Webview.asWebviewUri not working in Remote 
https://github.com/microsoft/vscode/issues/82336
=> Update vscode engine to -> 1.39.2

backend/package.json, frontend/jest.config.js, frontend/package.json, frontend/src/App.vue, frontend/src/components/QuestionTypes/QuestionInput.vue, frontend/tests/App.spec.js, frontend/tests/components/QuestionTypes/QuestionInput.spec.js
=> Revert "Password"

backend/.nycrc.json, backend/src/extension.ts, backend/src/yeomanui.ts, backend/tests/yeomanui.spec.ts, frontend/jest.config.js, frontend/src/App.vue, frontend/tests/App.spec.js
Issue: https://github.com/SAP/yeoman-ui/issues/105
=> issue #105 UI doesn't indicate installation of dependencies

frontend/src/components/GeneratorSelection.vue
=> Generator-Selection: v-card__title word-wrap break-word

backend/src/extension.ts
https://sapjira.wdf.sap.corp/browse/DEVXBUGS-6259
=> dispose panel instance - bug fix

backend/package.json, backend/src/vscode-youi-events.ts, backend/tests/extension.spec.ts, backend/tests/vscode-youi-events.spec.ts
=> 'Add to workspace' button in the end of wizard

frontend/src/assets/css/globalStyles.css, generator-foodq/generators/app/index.js
=> inquirer-gui-card-style

frontend/package.json
Update QuestionList to support Inquirer.Separator() with line = '──────────────'
=> inquirer-gui : 0.1.13 Update QuestionList Separator align left.

backend/package.json
=> Upgrade "@vscode-logging/logger" to "1.1.0".

backend/src/extension.ts, backend/src/logger/logger-wrapper.ts
=> Fix: unreadable log label

backend/package.json, backend/src/exploregens.ts, backend/src/extension.ts, backend/src/panels/YeomanUIPanel.ts, backend/src/yeomanui.ts, backend/tests/exploregens.spec.ts, backend/tests/extension.spec.ts, frontend/src/App.vue, frontend/tests/App.spec.js
=> update first generators prompt when a generator was added or removed

backend/package.json, backend/src/vscode-youi-events.ts, backend/src/webSocketServer/server-youi-events.ts, backend/src/yeomanui.ts, backend/src/youi-events.ts, backend/tests/vscode-youi-events.spec.ts, backend/tests/yeomanui.spec.ts, frontend/package.json, frontend/src/App.vue, frontend/tests/App.spec.js, generator-foodq/generators/app/index.js
=> feat: question-link

backend/.nycrc.json, backend/package.json, backend/src/extension.ts, backend/src/messages.ts, backend/src/panels/YeomanUIPanel.ts, backend/src/yeomanui.ts, backend/tests/yeomanui.spec.ts, frontend/jest.config.js, frontend/src/App.vue, frontend/tests/App.spec.js
=> feat: indicating generators are being installed in background

backend/src/vscode-youi-events.ts, backend/src/webSocketServer/index.ts, backend/src/webSocketServer/server-youi-events.ts, backend/src/yeomanui.ts, backend/src/youi-events.ts, backend/tests/vscode-youi-events.spec.ts, backend/tests/yeomanui.spec.ts, backend/tests/youi-adapter.spec.ts
Fix https://github.com/SAP/yeoman-ui/issues/516
=> fix: issues/516 run as websocket - Error: Cannot find module 'vscode'

backend/package.json, backend/src/exploregens.ts, backend/tests/exploregens.spec.ts
=> ci: revert "fix: install generator to a valid and absolute location

packages/types/tsconfig.json
Test release:version releases types to npm.
1. Create a PR with change in types/tsconfig.json “chore: test” - this PR.
2. Merge this PR to master.
3. Checkout master, fetch/rebase.
4. Invoke "yarn release:version".
5. Verify new types in npm.
=> chore: types - not expose the test folder

packages/frontend/src/assets/css/globalStyles.css, packages/frontend/src/components/Navigation.vue
Fixed according to UX requests
=> fix: style miss-alignments

packages/backend/package.json, packages/backend/src/utils/env.ts, packages/backend/webpack.config.js, yarn.lock
issue# DEVXBUGS-10444 - wizard UI fails in "easy UI5" template fixing
=> feat: support to yo-environment@3.10.0

packages/frontend/test/App.spec.js
Fixes publish, previous commit lint issue.
=> style(app.spec.js): removes whitespace

packages/backend/package.json, packages/backend/src/messages.ts, packages/backend/src/panels/YeomanUIPanel.ts, packages/backend/src/utils/generators-installation-progress.ts, packages/backend/test/utils/generators-installation-progress.spec.ts, yarn.lock
=> chore: get generators installation status from "@sap/bas-sdk" new api

packages/backend/package.json, packages/backend/src/yeomanui.ts, packages/backend/test/yeomanui.spec.ts
User can hide generators with a new setting
=> Hide generator from settings

packages/frontend/src/assets/css/globalStyles.css, packages/frontend/src/youi/App.vue
Issue: https://github.com/SAP/yeoman-ui/issues/719
=> style: color for error messages adjusted

package.json, yarn.lock
Addressing dependabot suggestions for tar-fs, vite, rollup and @babel/runtime
=> chore: address dependabot suggestions

packages/frontend/package.json, yarn.lock
Consume the latest Inquirer GUI v3.4.6
=> chore: consume inquirer-gui v3.4.6
